name: Python Only CI  

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
    - uses: actions/checkout@v3  
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version" 

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: debug ls dir
      run: ls -la

    - name: get sample dataset
      run: make load_sample_dataset
    
    - name: debug2 ls dir
      run: ls ./data/ -la

    - name: run project
      run: make build

    # - name: Run tests  
    #   run: pytest   
